# Generated by Django 6.0.2 on 2026-04-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('AWARENESS', 'Awareness Creation'), ('NCSAM', 'NCSAM'), ('CHALLENGE', 'Cybersecurity Challenge'), ('WORKSHOP', 'Workshop'), ('TRAINING', 'Training'), ('SENSITISATION', 'Sensitisation'), ('CYBER_HYGIENE', 'Cyber Hygiene'), ('OUTREACH', 'Outreach'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
