# Generated by Django 6.0.7 on 2026-08-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_eventregistration_check_in_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_paragraph_1', models.TextField(blank=True)),
                ('intro_paragraph_2', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('mandate_text', models.TextField(blank=True)),
                ('mission_text', models.TextField(blank=True)),
                ('vision_text', models.TextField(blank=True)),
                ('value_1_title', models.CharField(blank=True, max_length=100)),
                ('value_1_description', models.TextField(blank=True)),
                ('value_2_title', models.CharField(blank=True, max_length=100)),
                ('value_2_description', models.TextField(blank=True)),
                ('value_3_title', models.CharField(blank=True, max_length=100)),
                ('value_3_description', models.TextField(blank=True)),
                ('value_4_title', models.CharField(blank=True, max_length=100)),
                ('value_4_description', models.TextField(blank=True)),
                ('value_5_title', models.CharField(blank=True, max_length=100)),
                ('value_5_description', models.TextField(blank=True)),
                ('value_6_title', models.CharField(blank=True, max_length=100)),
                ('value_6_description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_address', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(default=5.6037)),
                ('longitude', models.FloatField(default=-0.187)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('emergency_hotline', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_channel_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
