# Generated by Django 6.0.7 on 2026-09-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_campaign_location_latitude_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpagecontent',
            name='latitude',
            field=models.FloatField(default=5.6037075),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='longitude',
            field=models.FloatField(default=-0.1764636),
        ),
    ]
