# Generated by Django 6.0.2 on 2026-04-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('ARCHIVED', 'Archived')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('ARCHIVED', 'Archived')], default='NEW', max_length=20),
        ),
    ]
