# Generated by Django 6.0.2 on 2026-04-06 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='date_of_incident',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='evidence_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='relationship_to_victim',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporting_for_someone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
    ]
