# Generated by Django 6.0.7 on 2026-08-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='holder_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
