# Generated by Django 6.0.7 on 2026-09-08 14:15

from django.db import migrations, models


def seed_existing_statuses(apps, schema_editor):
    # Matches the colors that were hardcoded in both the admin web app
    # and the mobile app before this table existed, so nothing visually
    # changes for these three — only newly-added statuses are new.
    IncidentStatusOption = apps.get_model('incidents', 'IncidentStatusOption')
    IncidentStatusOption.objects.bulk_create([
        IncidentStatusOption(key='PENDING', label='Pending', color='#D97706', position=0),
        IncidentStatusOption(key='UNDER_REVIEW', label='Under Review', color='#212060', position=1),
        IncidentStatusOption(key='RESOLVED', label='Resolved', color='#1A7F4B', position=2),
    ])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_rename_incident_region_to_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.RunPython(seed_existing_statuses, noop_reverse),
    ]
