# Generated by Django 6.0.7 on 2026-09-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_incidentstatusoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='incident_evidence/'),
        ),
    ]
