from django.urls import path

from .admin_views import (
    admin_campaign_check_in,
    admin_campaign_detail,
    admin_campaign_registrations,
    admin_campaigns_collection,
    admin_content_dashboard,
    admin_event_detail,
    admin_events_collection,
    admin_event_registrations,
    admin_check_in_registration,
    admin_campaign_gallery_create,
    admin_campaign_gallery_detail,
    admin_campaign_news_create,
    admin_campaign_news_detail,
    admin_news_collection,
    admin_news_detail,
    admin_press_collection,
    admin_press_detail,
    admin_campaign_schedule_create,
    admin_campaign_schedule_detail,
    admin_campaign_speaker_create,
    admin_campaign_speaker_detail,
    admin_about_page,
    admin_contact_page,
)

urlpatterns = [
    path(
        'admin/news/', admin_news_collection, name='admin_news_collection'
    ),
    path(
        'admin/news/<int:article_id>/',
        admin_news_detail,
        name='admin_news_detail',
    ),
    path(
        'admin/events/',
        admin_events_collection,
        name='admin_events_collection',
    ),
    path(
        'admin/events/<int:event_id>/',
        admin_event_detail,
        name='admin_event_detail',
    ),
    path(
        'admin/events/<int:event_id>/registrations/',
        admin_event_registrations,
        name='admin_event_registrations',
    ),
    path(
        'admin/events/<int:event_id>/check-in/',
        admin_check_in_registration,
        name='admin_check_in_registration',
    ),
    path(
        'admin/campaigns/',
        admin_campaigns_collection,
        name='admin_campaigns_collection',
    ),
    path(
        'admin/campaigns/<int:campaign_id>/',
        admin_campaign_detail,
        name='admin_campaign_detail',
    ),
    path(
        'admin/campaigns/<int:campaign_id>/registrations/',
        admin_campaign_registrations,
        name='admin_campaign_registrations',
    ),
    path(
        'admin/campaigns/<int:campaign_id>/check-in/',
        admin_campaign_check_in,
        name='admin_campaign_check_in',
    ),
    path(
        'admin/campaigns/<int:campaign_id>/gallery/',
        admin_campaign_gallery_create,
        name='admin_campaign_gallery_create',
    ),
    path(
        'admin/campaigns/gallery/<int:gallery_id>/',
        admin_campaign_gallery_detail,
        name='admin_campaign_gallery_detail',
    ),
    path(
        'admin/campaigns/<int:campaign_id>/schedule/',
        admin_campaign_schedule_create,
        name='admin_campaign_schedule_create',
    ),
    path(
        'admin/campaigns/schedule/<int:schedule_id>/',
        admin_campaign_schedule_detail,
        name='admin_campaign_schedule_detail',
    ),
    path(
        'admin/campaigns/<int:campaign_id>/speakers/',
        admin_campaign_speaker_create,
        name='admin_campaign_speaker_create',
    ),
    path(
        'admin/campaigns/speakers/<int:speaker_id>/',
        admin_campaign_speaker_detail,
        name='admin_campaign_speaker_detail',
    ),
    path(
        'admin/campaigns/<int:campaign_id>/related-news/',
        admin_campaign_news_create,
        name='admin_campaign_news_create',
    ),
    path(
        'admin/campaigns/related-news/<int:related_news_id>/',
        admin_campaign_news_detail,
        name='admin_campaign_news_detail',
    ),
    path(
        'admin/press-releases/',
        admin_press_collection,
        name='admin_press_collection',
    ),
    path(
        'admin/press-releases/<int:release_id>/',
        admin_press_detail,
        name='admin_press_detail',
    ),
    path(
        'admin/dashboard/content/',
        admin_content_dashboard,
        name='admin_content_dashboard',
    ),
    path('admin/content/about/', admin_about_page, name='admin_about_page'),
    path(
        'admin/content/contact/',
        admin_contact_page,
        name='admin_contact_page',
    ),
]
