# Generated by Django 6.0.7 on 2026-08-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('BUG_REPORT', 'Bug Report'), ('SUGGESTION', 'Suggestion'), ('QUESTION', 'Question'), ('COMPLIMENT', 'Compliment'), ('APP_RATING', 'App Rating')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
